# Generated by Django 4.0.2 on 2022-02-25 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_of_publish', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('is_bestseller', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='author.author')),
            ],
        ),
    ]
